import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { Toaster } from "react-hot-toast"
import PageProtector from "@/components/PageProtector"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PageProtector>
          {children}
          <Toaster
            toastOptions={{
              position: "bottom-center",
              style: {
                background: "#333",
                color: "white",
              },
            }}
          />
        </PageProtector>
      </body>
    </html>
  )
}
